<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta.phtml' ?>

<ul class="list-group">
<?php foreach($albumes as $album): ?>
    <li class="list-group-item item-album <?php if($album->albumes): ?> albumes <?php endif ?>">
        <div>
        <b><?= $album->tituloAlbum ?></b> | Duración: <?= $album->añoLanzamiento ?> | Álbum ID: <?= $album->albumID ?>
        </div>
        <div class="actions">
            <a href="eliminar/<?= $album->ID ?>" type="button" class='btn btn-danger ' >Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> albumes</small></p>

<?php require 'templates/footer.phtml' ?>

