<?php require 'templates/header.phtml'; ?>

<div class="container-fluid w-100 d-flex justify-content-center">
    <div>
        <h1>Editar Albumes</h1>
        <table class="my-4 table">
            <thead>
                <tr>
                    <th class="col">Título</th>
                    <th class="col">Año lanzamiento</th>
                    <th class="col">Artista al que pertenece</th>
                    <th class="col">ACTUALIZAR</th>
                </tr>
            </thead>

            <?php foreach ($albumes as $album): ?>
                <form class="form-alta" action="editarAlbum/<?= $album->ID ?>" method="POST">
                    <tr style="text-align:center">
                        <td><input class="form-control" type="text" name="tituloAlbum" value="<?= $album->tituloAlbum ?>"></td>
                        <td><input class="form-control" type="text" name="anioLanzamiento" value="<?= $album->anioLanzamiento ?>"></td>
                        <td>
                            <select class="form-control" name="artistaID">
                                <?php foreach ($albumes as $artista): ?>
                                    <option value="<?= $artista->ID ?>" <?= $album->artistaID == $artista->ID ? 'selected' : '' ?>>
                                        <?= $artista->nombreArtista ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><a href="actualizarCancion/<?= $canciones->ID ?>"  type="button" class="btn btn-warning">Actualizar</a></td>   
                    </tr>
                </form>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<a href=""  type="submit" class="btn btn-primary">volver</a>
<?php require 'templates/footer.phtml'; ?>
