<?php require 'templates/header.phtml'; ?>

<div class="container-fluid w-100 d-flex justify-content-center">
    <div>
        <h1>Editar Canciones</h1>
        <table class="my-4 table">
            <thead>
                <tr>
                    <th class="col">Título</th>
                    <th class="col">Álbum</th>
                    <th class="col">Duración</th>
                    <th class="col">ACTUALIZAR</th>

                </tr>
            </thead>

                <form class="form-alta" action="actualizarCancion/<?= $canciones->ID ?>" method="POST">
                    <tr style="text-align:center">
                        <td><input class="form-control" type="text" name="nuevoTitulo" value="<?= $canciones->titulo ?>"></td>
                        <td>
                            <select class="form-control" name="nuevoAlbum">
                                <?php foreach ($albumes as $album): ?>
                                    <option value="<?= $album->ID ?>" <?= $canciones->albumID == $album->ID ? 'selected' : '' ?>>
                                        <?= $album->tituloAlbum ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><input class="form-control" type="text" name="nuevoDuracion" value="<?= $canciones->Duración ?>"></td>
                        <td> <button type="submit"  class="btn btn-warning">Actualizar </button> </td> 
                                 
                    </tr>
                </form>
        </table>
    </div>
</div>
<a href=""  type="submit" class="btn btn-primary">volver</a>
<?php require 'templates/footer.phtml'; ?>
